@username = root
@password = supasekret

###
GET http://localhost:3001/api/users
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "dummy",
  "name": "tyhäm",
  "password": "xxx"
}